name: Lint Go Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          stable: 'false'
          go-version: '1.21.1'

      - name: lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

          golangci-lint run
